// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/providers/profile_videos_auto_load_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i14;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:nostr_sdk/event.dart' as _i7;
import 'package:nostr_sdk/filter.dart' as _i8;
import 'package:openvine/models/nip94_metadata.dart' as _i9;
import 'package:openvine/models/video_event.dart' as _i12;
import 'package:openvine/services/content_blocklist_service.dart' as _i13;
import 'package:openvine/services/nostr_key_manager.dart' as _i2;
import 'package:openvine/services/nostr_service.dart' as _i4;
import 'package:openvine/services/nostr_service_interface.dart' as _i3;
import 'package:openvine/services/p2p_discovery_service.dart' as _i10;
import 'package:openvine/services/video_event_service.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNostrKeyManager_0 extends _i1.SmartFake
    implements _i2.NostrKeyManager {
  _FakeNostrKeyManager_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNostrBroadcastResult_1 extends _i1.SmartFake
    implements _i3.NostrBroadcastResult {
  _FakeNostrBroadcastResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NostrService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNostrService extends _i1.Mock implements _i4.NostrService {
  MockNostrService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get isDisposed =>
      (super.noSuchMethod(Invocation.getter(#isDisposed), returnValue: false)
          as bool);

  @override
  List<String> get connectedRelays =>
      (super.noSuchMethod(
            Invocation.getter(#connectedRelays),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  bool get hasKeys =>
      (super.noSuchMethod(Invocation.getter(#hasKeys), returnValue: false)
          as bool);

  @override
  _i2.NostrKeyManager get keyManager =>
      (super.noSuchMethod(
            Invocation.getter(#keyManager),
            returnValue: _FakeNostrKeyManager_0(
              this,
              Invocation.getter(#keyManager),
            ),
          )
          as _i2.NostrKeyManager);

  @override
  int get relayCount =>
      (super.noSuchMethod(Invocation.getter(#relayCount), returnValue: 0)
          as int);

  @override
  int get connectedRelayCount =>
      (super.noSuchMethod(
            Invocation.getter(#connectedRelayCount),
            returnValue: 0,
          )
          as int);

  @override
  List<String> get relays =>
      (super.noSuchMethod(Invocation.getter(#relays), returnValue: <String>[])
          as List<String>);

  @override
  Map<String, dynamic> get relayStatuses =>
      (super.noSuchMethod(
            Invocation.getter(#relayStatuses),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  Map<String, bool> get relayAuthStates =>
      (super.noSuchMethod(
            Invocation.getter(#relayAuthStates),
            returnValue: <String, bool>{},
          )
          as Map<String, bool>);

  @override
  _i5.Stream<Map<String, bool>> get authStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#authStateStream),
            returnValue: _i5.Stream<Map<String, bool>>.empty(),
          )
          as _i5.Stream<Map<String, bool>>);

  @override
  bool get isVineRelayAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isVineRelayAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  String get primaryRelay =>
      (super.noSuchMethod(
            Invocation.getter(#primaryRelay),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#primaryRelay),
            ),
          )
          as String);

  @override
  _i5.Future<void> initialize({
    List<String>? customRelays,
    bool? enableP2P = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {
              #customRelays: customRelays,
              #enableP2P: enableP2P,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool isRelayAuthenticated(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#isRelayAuthenticated, [relayUrl]),
            returnValue: false,
          )
          as bool);

  @override
  void setAuthTimeout(Duration? timeout) => super.noSuchMethod(
    Invocation.method(#setAuthTimeout, [timeout]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Stream<_i7.Event> subscribeToEvents({
    required List<_i8.Filter>? filters,
    bool? bypassLimits = false,
    void Function()? onEose,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToEvents, [], {
              #filters: filters,
              #bypassLimits: bypassLimits,
              #onEose: onEose,
            }),
            returnValue: _i5.Stream<_i7.Event>.empty(),
          )
          as _i5.Stream<_i7.Event>);

  @override
  _i5.Future<_i3.NostrBroadcastResult> broadcastEvent(_i7.Event? event) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastEvent, [event]),
            returnValue: _i5.Future<_i3.NostrBroadcastResult>.value(
              _FakeNostrBroadcastResult_1(
                this,
                Invocation.method(#broadcastEvent, [event]),
              ),
            ),
          )
          as _i5.Future<_i3.NostrBroadcastResult>);

  @override
  _i5.Future<_i3.NostrBroadcastResult> publishFileMetadata({
    required _i9.NIP94Metadata? metadata,
    required String? content,
    List<String>? hashtags = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#publishFileMetadata, [], {
              #metadata: metadata,
              #content: content,
              #hashtags: hashtags,
            }),
            returnValue: _i5.Future<_i3.NostrBroadcastResult>.value(
              _FakeNostrBroadcastResult_1(
                this,
                Invocation.method(#publishFileMetadata, [], {
                  #metadata: metadata,
                  #content: content,
                  #hashtags: hashtags,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.NostrBroadcastResult>);

  @override
  _i5.Future<bool> addRelay(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#addRelay, [relayUrl]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> retryInitialization() =>
      (super.noSuchMethod(
            Invocation.method(#retryInitialization, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removeRelay(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#removeRelay, [relayUrl]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  Map<String, bool> getRelayStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayStatus, []),
            returnValue: <String, bool>{},
          )
          as Map<String, bool>);

  @override
  _i5.Future<void> reconnectAll() =>
      (super.noSuchMethod(
            Invocation.method(#reconnectAll, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> closeAllSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#closeAllSubscriptions, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<_i7.Event> searchVideos(
    String? query, {
    List<String>? authors,
    DateTime? since,
    DateTime? until,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchVideos,
              [query],
              {#authors: authors, #since: since, #until: until, #limit: limit},
            ),
            returnValue: _i5.Stream<_i7.Event>.empty(),
          )
          as _i5.Stream<_i7.Event>);

  @override
  _i5.Future<Map<String, dynamic>?> getRelayStats() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayStats, []),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<bool> startP2PDiscovery() =>
      (super.noSuchMethod(
            Invocation.method(#startP2PDiscovery, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> stopP2PDiscovery() =>
      (super.noSuchMethod(
            Invocation.method(#stopP2PDiscovery, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> startP2PAdvertising() =>
      (super.noSuchMethod(
            Invocation.method(#startP2PAdvertising, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> stopP2PAdvertising() =>
      (super.noSuchMethod(
            Invocation.method(#stopP2PAdvertising, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  List<_i10.P2PPeer> getP2PPeers() =>
      (super.noSuchMethod(
            Invocation.method(#getP2PPeers, []),
            returnValue: <_i10.P2PPeer>[],
          )
          as List<_i10.P2PPeer>);

  @override
  _i5.Future<bool> connectToP2PPeer(_i10.P2PPeer? peer) =>
      (super.noSuchMethod(
            Invocation.method(#connectToP2PPeer, [peer]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> syncWithP2PPeers() =>
      (super.noSuchMethod(
            Invocation.method(#syncWithP2PPeers, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> startAutoP2PSync({
    Duration? interval = const Duration(minutes: 5),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startAutoP2PSync, [], {#interval: interval}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> stopAutoP2PSync() =>
      (super.noSuchMethod(
            Invocation.method(#stopAutoP2PSync, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.Event>> getEvents({
    required List<_i8.Filter>? filters,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEvents, [], {
              #filters: filters,
              #limit: limit,
            }),
            returnValue: _i5.Future<List<_i7.Event>>.value(<_i7.Event>[]),
          )
          as _i5.Future<List<_i7.Event>>);

  @override
  _i5.Future<void> discoverUserRelays(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#discoverUserRelays, [pubkey]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> discoverRelaysFromEventHints(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#discoverRelaysFromEventHints, [pubkey]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [VideoEventService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoEventService extends _i1.Mock implements _i11.VideoEventService {
  MockVideoEventService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i12.VideoEvent> get homeFeedVideos =>
      (super.noSuchMethod(
            Invocation.getter(#homeFeedVideos),
            returnValue: <_i12.VideoEvent>[],
          )
          as List<_i12.VideoEvent>);

  @override
  List<_i12.VideoEvent> get discoveryVideos =>
      (super.noSuchMethod(
            Invocation.getter(#discoveryVideos),
            returnValue: <_i12.VideoEvent>[],
          )
          as List<_i12.VideoEvent>);

  @override
  List<_i12.VideoEvent> get profileVideos =>
      (super.noSuchMethod(
            Invocation.getter(#profileVideos),
            returnValue: <_i12.VideoEvent>[],
          )
          as List<_i12.VideoEvent>);

  @override
  List<_i12.VideoEvent> get editorialVideos =>
      (super.noSuchMethod(
            Invocation.getter(#editorialVideos),
            returnValue: <_i12.VideoEvent>[],
          )
          as List<_i12.VideoEvent>);

  @override
  List<_i12.VideoEvent> get popularNowVideos =>
      (super.noSuchMethod(
            Invocation.getter(#popularNowVideos),
            returnValue: <_i12.VideoEvent>[],
          )
          as List<_i12.VideoEvent>);

  @override
  List<_i12.VideoEvent> get trendingVideos =>
      (super.noSuchMethod(
            Invocation.getter(#trendingVideos),
            returnValue: <_i12.VideoEvent>[],
          )
          as List<_i12.VideoEvent>);

  @override
  List<_i12.VideoEvent> get allHashtagVideos =>
      (super.noSuchMethod(
            Invocation.getter(#allHashtagVideos),
            returnValue: <_i12.VideoEvent>[],
          )
          as List<_i12.VideoEvent>);

  @override
  List<_i12.VideoEvent> get searchResults =>
      (super.noSuchMethod(
            Invocation.getter(#searchResults),
            returnValue: <_i12.VideoEvent>[],
          )
          as List<_i12.VideoEvent>);

  @override
  List<_i12.VideoEvent> get videoEvents =>
      (super.noSuchMethod(
            Invocation.getter(#videoEvents),
            returnValue: <_i12.VideoEvent>[],
          )
          as List<_i12.VideoEvent>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  String get classicVinesPubkey =>
      (super.noSuchMethod(
            Invocation.getter(#classicVinesPubkey),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#classicVinesPubkey),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setBlocklistService(_i13.ContentBlocklistService? blocklistService) =>
      super.noSuchMethod(
        Invocation.method(#setBlocklistService, [blocklistService]),
        returnValueForMissingStub: null,
      );

  @override
  List<_i12.VideoEvent> getVideos(_i11.SubscriptionType? type) =>
      (super.noSuchMethod(
            Invocation.method(#getVideos, [type]),
            returnValue: <_i12.VideoEvent>[],
          )
          as List<_i12.VideoEvent>);

  @override
  List<_i12.VideoEvent> hashtagVideos(String? tag) =>
      (super.noSuchMethod(
            Invocation.method(#hashtagVideos, [tag]),
            returnValue: <_i12.VideoEvent>[],
          )
          as List<_i12.VideoEvent>);

  @override
  List<_i12.VideoEvent> authorVideos(String? pubkeyHex) =>
      (super.noSuchMethod(
            Invocation.method(#authorVideos, [pubkeyHex]),
            returnValue: <_i12.VideoEvent>[],
          )
          as List<_i12.VideoEvent>);

  @override
  bool isLoadingForSubscription(_i11.SubscriptionType? subscriptionType) =>
      (super.noSuchMethod(
            Invocation.method(#isLoadingForSubscription, [subscriptionType]),
            returnValue: false,
          )
          as bool);

  @override
  bool hasEvents(_i11.SubscriptionType? type) =>
      (super.noSuchMethod(
            Invocation.method(#hasEvents, [type]),
            returnValue: false,
          )
          as bool);

  @override
  int getEventCount(_i11.SubscriptionType? type) =>
      (super.noSuchMethod(
            Invocation.method(#getEventCount, [type]),
            returnValue: 0,
          )
          as int);

  @override
  bool isSubscribed(_i11.SubscriptionType? type) =>
      (super.noSuchMethod(
            Invocation.method(#isSubscribed, [type]),
            returnValue: false,
          )
          as bool);

  @override
  List<_i12.VideoEvent> getVideosByAuthor(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getVideosByAuthor, [pubkey]),
            returnValue: <_i12.VideoEvent>[],
          )
          as List<_i12.VideoEvent>);

  @override
  _i5.Future<void> subscribeToVideoFeed({
    required _i11.SubscriptionType? subscriptionType,
    List<String>? authors,
    List<String>? hashtags,
    String? group,
    int? since,
    int? until,
    int? limit = 200,
    bool? replace = true,
    bool? includeReposts = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToVideoFeed, [], {
              #subscriptionType: subscriptionType,
              #authors: authors,
              #hashtags: hashtags,
              #group: group,
              #since: since,
              #until: until,
              #limit: limit,
              #replace: replace,
              #includeReposts: includeReposts,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> subscribeToUserVideos(String? pubkey, {int? limit = 50}) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribeToUserVideos,
              [pubkey],
              {#limit: limit},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> subscribeToHashtagVideos(
    List<String>? hashtags, {
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribeToHashtagVideos,
              [hashtags],
              {#limit: limit},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> subscribeToHomeFeed(
    List<String>? followingPubkeys, {
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribeToHomeFeed,
              [followingPubkeys],
              {#limit: limit},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> subscribeToDiscovery({int? limit = 100}) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToDiscovery, [], {#limit: limit}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> subscribeToGroupVideos(
    String? group, {
    List<String>? authors,
    int? since,
    int? until,
    int? limit = 200,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribeToGroupVideos,
              [group],
              {#authors: authors, #since: since, #until: until, #limit: limit},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  List<_i12.VideoEvent> getVideoEventsByGroup(String? group) =>
      (super.noSuchMethod(
            Invocation.method(#getVideoEventsByGroup, [group]),
            returnValue: <_i12.VideoEvent>[],
          )
          as List<_i12.VideoEvent>);

  @override
  _i5.Future<void> refreshVideoFeed() =>
      (super.noSuchMethod(
            Invocation.method(#refreshVideoFeed, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> loadMoreVideos({int? limit = 100}) =>
      (super.noSuchMethod(
            Invocation.method(#loadMoreVideos, [], {#limit: limit}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> loadMoreEvents(
    _i11.SubscriptionType? subscriptionType, {
    int? limit = 500,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #loadMoreEvents,
              [subscriptionType],
              {#limit: limit},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void resetPaginationState(_i11.SubscriptionType? subscriptionType) =>
      super.noSuchMethod(
        Invocation.method(#resetPaginationState, [subscriptionType]),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> loadMoreContentUnlimited({
    _i11.SubscriptionType? subscriptionType = _i11.SubscriptionType.discovery,
    int? limit = 300,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadMoreContentUnlimited, [], {
              #subscriptionType: subscriptionType,
              #limit: limit,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i12.VideoEvent? getVideoEventById(String? eventId) =>
      (super.noSuchMethod(Invocation.method(#getVideoEventById, [eventId]))
          as _i12.VideoEvent?);

  @override
  _i12.VideoEvent? getVideoEventByVineId(String? vineId) =>
      (super.noSuchMethod(Invocation.method(#getVideoEventByVineId, [vineId]))
          as _i12.VideoEvent?);

  @override
  _i5.Future<_i12.VideoEvent?> queryVideoByVineId(String? vineId) =>
      (super.noSuchMethod(
            Invocation.method(#queryVideoByVineId, [vineId]),
            returnValue: _i5.Future<_i12.VideoEvent?>.value(),
          )
          as _i5.Future<_i12.VideoEvent?>);

  @override
  List<_i12.VideoEvent> getVideoEventsByAuthor(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getVideoEventsByAuthor, [pubkey]),
            returnValue: <_i12.VideoEvent>[],
          )
          as List<_i12.VideoEvent>);

  @override
  List<_i12.VideoEvent> getVideoEventsByHashtags(List<String>? hashtags) =>
      (super.noSuchMethod(
            Invocation.method(#getVideoEventsByHashtags, [hashtags]),
            returnValue: <_i12.VideoEvent>[],
          )
          as List<_i12.VideoEvent>);

  @override
  void clearVideoEvents() => super.noSuchMethod(
    Invocation.method(#clearVideoEvents, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> unsubscribeFromVideoFeed() =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribeFromVideoFeed, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  List<_i12.VideoEvent> getVideoEventsByEngagement() =>
      (super.noSuchMethod(
            Invocation.method(#getVideoEventsByEngagement, []),
            returnValue: <_i12.VideoEvent>[],
          )
          as List<_i12.VideoEvent>);

  @override
  List<_i12.VideoEvent> getRecentVideoEvents({int? hours = 24}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentVideoEvents, [], {#hours: hours}),
            returnValue: <_i12.VideoEvent>[],
          )
          as List<_i12.VideoEvent>);

  @override
  Set<String> getUniqueAuthors() =>
      (super.noSuchMethod(
            Invocation.method(#getUniqueAuthors, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Set<String> getAllHashtags() =>
      (super.noSuchMethod(
            Invocation.method(#getAllHashtags, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Map<String, int> getVideoCountByAuthor() =>
      (super.noSuchMethod(
            Invocation.method(#getVideoCountByAuthor, []),
            returnValue: <String, int>{},
          )
          as Map<String, int>);

  @override
  Map<String, dynamic> getConnectionStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getConnectionStatus, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i5.Future<void> retrySubscription() =>
      (super.noSuchMethod(
            Invocation.method(#retrySubscription, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void shuffleForDiscovery() => super.noSuchMethod(
    Invocation.method(#shuffleForDiscovery, []),
    returnValueForMissingStub: null,
  );

  @override
  void addVideoEvent(_i12.VideoEvent? videoEvent) => super.noSuchMethod(
    Invocation.method(#addVideoEvent, [videoEvent]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> searchVideos(
    String? query, {
    List<String>? authors,
    DateTime? since,
    DateTime? until,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchVideos,
              [query],
              {#authors: authors, #since: since, #until: until, #limit: limit},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> searchVideosByHashtag(String? hashtag) =>
      (super.noSuchMethod(
            Invocation.method(#searchVideosByHashtag, [hashtag]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> searchVideosWithFilters({
    required String? query,
    List<String>? authors,
    DateTime? since,
    DateTime? until,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchVideosWithFilters, [], {
              #query: query,
              #authors: authors,
              #since: since,
              #until: until,
              #limit: limit,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void clearSearchResults() => super.noSuchMethod(
    Invocation.method(#clearSearchResults, []),
    returnValueForMissingStub: null,
  );

  @override
  List<_i12.VideoEvent> processSearchResults(List<_i7.Event>? events) =>
      (super.noSuchMethod(
            Invocation.method(#processSearchResults, [events]),
            returnValue: <_i12.VideoEvent>[],
          )
          as List<_i12.VideoEvent>);

  @override
  List<_i12.VideoEvent> deduplicateSearchResults(
    List<_i12.VideoEvent>? results,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deduplicateSearchResults, [results]),
            returnValue: <_i12.VideoEvent>[],
          )
          as List<_i12.VideoEvent>);

  @override
  _i5.Future<void> searchVideosWithTimeRange({
    required String? query,
    required DateTime? since,
    required DateTime? until,
    List<String>? authors,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchVideosWithTimeRange, [], {
              #query: query,
              #since: since,
              #until: until,
              #authors: authors,
              #limit: limit,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> searchVideosWithExtensions(String? queryWithExtensions) =>
      (super.noSuchMethod(
            Invocation.method(#searchVideosWithExtensions, [
              queryWithExtensions,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  Map<_i11.SubscriptionType, _i11.PaginationState>
  getPaginationStatesForTesting() =>
      (super.noSuchMethod(
            Invocation.method(#getPaginationStatesForTesting, []),
            returnValue: <_i11.SubscriptionType, _i11.PaginationState>{},
          )
          as Map<_i11.SubscriptionType, _i11.PaginationState>);

  @override
  void addVideoEventForTesting(
    _i12.VideoEvent? event,
    _i11.SubscriptionType? type, {
    required bool? isHistorical,
  }) => super.noSuchMethod(
    Invocation.method(
      #addVideoEventForTesting,
      [event, type],
      {#isHistorical: isHistorical},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void injectTestVideos(List<_i12.VideoEvent>? videos) => super.noSuchMethod(
    Invocation.method(#injectTestVideos, [videos]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
